use_frameworks!

platform :ios, '10.0'

target 'DEACRollingNumberLabel_Example' do
  pod 'DEACRollingNumberLabel', :path => '../'

  target 'DEACRollingNumberLabel_Tests' do
    inherit! :search_paths

    
  end
end
